name: GitHub_Actions(bot)
on:
  workflow_dispatch:
  #schedule:
    #- cron: "*/10 0-11 * * 1-6"
            #"*/10 2-10 * * 1-5" 12時〜20時、10分ごとに動作
env:  #環境変数から文字列(パスワードなど)を取得
  DISCORD_TOKEN2: ${{secrets.DISCORD_TOKEN2}}
  DISCORD_ID_DEBUG: ${{secrets.DISCORD_ID_DEBUG}}
  JSON: ${{secrets.JSON}}
  CLIENT: ${{secrets.CLIENT}}

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install discord.py==1.7.3
          pip install pydrive==1.3.1
          python bot.py
