name: selenium-github-actions
on:
  workflow_dispatch:
env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
  E_MAIL: ${{secrets.E_MAIL}}
  GOOGLE_URL: ${{secrets.GOOGLE_URL}}
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install python-dotenv
          pip install selenium
          pip install tweepy
          pip install pillow
          pip install mega.py
          pip install opencv-python
          python image_test.py
